name: flutter_video_editor_test_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_editor: ^2.2.0

  helpers: ^1.2.0
  image_picker: ^0.8.6+1
  video_player: ^2.5.1
  fraction: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
